# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simpleflow}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["neyric"]
  s.date = %q{2010-08-27}
  s.description = %q{Simpleflow has a simple engine that executes modules in a loop. The workflows are declarative, which means that you can static-check them and safely run user workflows. Modules are created easily in ruby so you can quickly write wrappers around libraires.}
  s.email = %q{eric.abouaf@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/simpleflow.rb",
     "lib/simpleflow/dns_resolve.rb",
     "lib/simpleflow/http.rb",
     "lib/simpleflow/json.rb",
     "lib/simpleflow/jsonpath.rb",
     "lib/simpleflow/liquid.rb",
     "lib/simpleflow/object_builder.rb",
     "lib/simpleflow/ping.rb",
     "lib/simpleflow/string_builder.rb",
     "lib/simpleflow/urlencode.rb",
     "lib/simpleflow/yql.rb",
     "simpleflow.gemspec",
     "test/helper.rb",
     "test/test_simpleflow.rb"
  ]
  s.homepage = %q{http://github.com/neyric/simpleflow}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple workflow execution}
  s.test_files = [
    "test/helper.rb",
     "test/test_simpleflow.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

